name: Testing push http notification

on:
  push:
  workflow_dispatch:

jobs:
  local-test:
    name: Test from local source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: echo "${{ secrets.CLOUD_FUNCTION_INVOKER_KEY }}" | base64 --decode > key.json
      - uses: ./
        id: gcp-cloud-function-post
        with:
          cloud_function_url: ${{ secrets.CLOUD_FUNCTION_URL }}
          json_body: '{"test":"abc"}'

      - name: verify
        run: echo "Status ${{steps.gcp-cloud-function-post.outputs.result}}"

      - uses: ./
        id: gcp-cloud-function-post-key-value
        with:
          cloud_function_url: ${{ secrets.CLOUD_FUNCTION_URL }}
          key_value: |
            SOURCE=LOCAL,
            KEY1=VALUE1,
            KEY2=VALUE2,
            KEY3=VALUE3

      - name: parsed input
        run: echo "Status ${{steps.gcp-cloud-function-post-key-value.outputs.parsed_input}}"

      - name: verify
        run: echo "Status ${{steps.gcp-cloud-function-post-key-value.outputs.result}}"
  last-release-test:
    name: Last Release Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: echo "${{ secrets.CLOUD_FUNCTION_INVOKER_KEY }}" | base64 --decode > key.json
      - uses: lucatodeschini/gcp-cloud-function-post@main
        id: gcp-cloud-function-post
        with:
          cloud_function_url: ${{ secrets.CLOUD_FUNCTION_URL }}
          json_body: '{"test":"abc"}'

      - name: verify
        run: echo "Status ${{steps.gcp-cloud-function-post.outputs.result}}"

      - uses: lucatodeschini/gcp-cloud-function-post@v0.0.4
        id: gcp-cloud-function-post-key-value
        with:
          cloud_function_url: ${{ secrets.CLOUD_FUNCTION_URL }}
          key_value: |
            SOURCE=RELEASE,
            KEY1=VALUE1,
            KEY2=VALUE2,
            KEY3=VALUE3

      - name: parsed input
        run: echo "Status ${{steps.gcp-cloud-function-post-key-value.outputs.parsed_input}}"

      - name: verify
        run: echo "Status ${{steps.gcp-cloud-function-post-key-value.outputs.result}}"

